### ISSUE TITLE
Server fails to launch with BepInEx installed.

### ISSUE THREAD

**Issue by Seshnik** [AndrewSav/vrising-docker#1]
Hello Andrew, 

I came here from TrueOsiris's docker image after seeing you had gotten mods to work for yourself.
I then discovered your docker, I tried it out and set it up but sadly when using BepInEx, the server doesn't come online.

No logs either.
The moment i strip the BepInEx install out of the /mods directory and restart the docker, the server boots normally.
Unsure on what I'm doing wrong specifically.

Any help would be appreciated.

My script for the docker:

```
#!/bin/bash

sudo docker run -d --name='vrising' \
--net='bridge' \
--init \
--restart=unless-stopped \
-e TZ="Europe/London" \
-e SERVERNAME="Test Rising" \
-e ENABLE_MODS="true" \
-v '/root/servers/vrising-docker/server':'/mnt/vrising/server':'rw' \
-v '/root/servers/vrising-docker/persistentdata':'/mnt/vrising/persistentdata':'rw' \
-v '/root/servers/vrising-docker/mods':'/mnt/vrising/mods' \
-p 9876:9876/udp \
-p 9877:9877/udp \
'andrewsav/vrising'
```

**Comment by AndrewSav** [comment]
I'm not sure if I can help. The obvious suggestion is to try and follow the steps in the [Mods Support](https://github.com/AndrewSav/vrising-docker?tab=readme-ov-file#mods-support) section, but I'm assuming you have already done that.

I just fired up the server, deleted the mods folder and then followed the steps linked above and it worked for me again. The server went up and I was able to connect with the client. Here is my `docker-compose.yaml`:

```yaml
services:
  vrising:
    image: andrewsav/vrising
    init: true
    container_name: vrising3
    restart: unless-stopped
    network_mode: bridge
    environment:
      TZ: Pacific/Auckland
      VR_SERVER_NAME: redacted
      VR_GAME_PORT: "27019"
      VR_QUERY_PORT: "27020"
      VR_LIST_ON_STEAM: "true"
      VR_LIST_ON_EOS: "true"
      VR_MAX_USERS: "10"
      VR_PASSWORD: "redacted"
      VR_PRESET: StandardPvE
      VR_DIFFICULTY_PRESET: Difficulty_Normal
      ENABLE_MODS: 1
    volumes:
      - './server:/mnt/vrising/server'
      - './data:/mnt/vrising/persistentdata'
      - './mods:/mnt/vrising/mods'
    ports:
      - '27019:27019/udp'
      - '27020:27020/udp'
      - '25575:25575/tcp'
```
If you have any particular ideas how I can help, please do not hesitate to share them.
